"""vLLM backend: continuous batching for the graph protocol.

Scope limit, stated here because it must appear in the paper too. This backend is for
the **graph protocol**, whose numbers are compared only against other arms generated by
the same backend in the same run. The strict direct Leak@k compatibility runner stays
on ``transformers`` at batch size 1: vLLM's sampler, kernels and batching do not
reproduce ``model.generate`` bit for bit, and a result presented as a reproduction of
the released Leak@k generation path has to be one.

``vllm`` is imported lazily. The CPU gate must import this module without the package
installed, so that a missing wheel fails at construction with a useful message rather
than at import with a traceback in an unrelated test.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from .backend import GenRequest, GenResponse

__all__ = ["VllmBackend"]


class VllmBackend:
    name = "vllm"

    def __init__(
        self,
        model_path: str,
        *,
        profiles: Sequence[str] = ("primary",),
        revision: str | None = None,
        tokenizer: str | None = None,
        tokenizer_revision: str | None = None,
        dtype: str = "bfloat16",
        gpu_memory_utilization: float = 0.82,
        max_model_len: int = 2048,
        max_num_seqs: int = 32,
        max_num_batched_tokens: int | None = 8192,
        tensor_parallel_size: int = 1,
        engine: Any | None = None,
    ) -> None:
        self.model_path = model_path
        self.revision = revision
        self.tokenizer_path = tokenizer or model_path
        self.tokenizer_revision = tokenizer_revision
        # Every logical agent profile maps to ONE engine. Five agents, one checkpoint.
        self.profiles = tuple(profiles)
        self._engine = engine
        self._resolved: dict[str, str | None] | None = None
        self._accepts_use_tqdm = True
        # `tokenizer_revision` was previously accepted by the CLI, recorded in the
        # manifest, and never passed here — so the engine loaded the tokenizer from the
        # branch head while the manifest claimed a pinned commit, and every serialized
        # prompt hash was attributed to a chat template that may not have rendered it.
        # Annotated `dict[str, Any]`, not left to inference. Inference widens this to
        # `dict[str, float | int | str]`, and because `dict` is invariant mypy then
        # rejects the `LLM(**kwargs)` splat in `_ensure_engine` against every one of
        # vLLM's parameter types — but ONLY on a box where vllm is installed, which the
        # CPU gate never is. See the note in `_ensure_engine`.
        self._engine_kwargs: dict[str, Any] = {
            "model": model_path,
            "revision": revision,
            "tokenizer": self.tokenizer_path,
            "tokenizer_revision": tokenizer_revision,
            "dtype": dtype,
            "gpu_memory_utilization": gpu_memory_utilization,
            "max_model_len": max_model_len,
            "max_num_seqs": max_num_seqs,
            "max_num_batched_tokens": max_num_batched_tokens,
            "tensor_parallel_size": tensor_parallel_size,
        }
        # NOTE: no token argument. Authentication comes from HF_TOKEN in the process
        # environment or from an already-authenticated cache, so a credential can never
        # be captured into engine kwargs and from there into a manifest.

    # ------------------------------------------------------------------- lifecycle --

    def _ensure_engine(self) -> Any:
        if self._engine is None:
            try:
                from vllm import LLM
            except ImportError as exc:  # pragma: no cover - GPU-only path
                raise ImportError(
                    "the vllm backend requires the `vllm` package. Install it on the GPU "
                    "box, or set runtime.backend=transformers in the active profile."
                ) from exc
            kwargs = {k: v for k, v in self._engine_kwargs.items() if v is not None}
            self._engine = LLM(**kwargs)
        return self._engine

    # ------------------------------------------------------------------ generation --

    def generate(self, requests: Sequence[GenRequest]) -> list[GenResponse]:
        if not requests:
            return []
        engine = self._ensure_engine()
        try:
            from vllm import SamplingParams
        except ImportError:  # pragma: no cover - satisfied by the injected test engine
            # `misc` as well as `assignment`: when vllm IS installed the imported name is
            # a real class, and rebinding it is "Cannot assign to a type" [misc] rather
            # than an assignment error. `warn_unused_ignores = false`, so the extra code
            # stays silent on a CPU box where the import fails and the name is Any.
            SamplingParams = _SamplingParamsShim  # type: ignore[assignment,misc]

        prompts: list[str] = []
        params: list[Any] = []
        for request in requests:
            prompts.append(self._render(request))
            params.append(
                SamplingParams(
                    n=1,
                    temperature=(request.temperature if request.do_sample else 0.0) or 0.0,
                    top_p=request.top_p if request.top_p is not None else 1.0,
                    # vLLM spells "disabled" as -1; the repo's convention is 0.
                    top_k=-1 if not request.top_k else request.top_k,
                    max_tokens=request.max_new_tokens,
                    seed=request.seed,
                )
            )
        outputs = self._dispatch(engine, prompts, params)
        if len(outputs) != len(requests):
            raise RuntimeError(f"vllm returned {len(outputs)} outputs for {len(requests)} prompts")
        responses: list[GenResponse] = []
        for request, output in zip(requests, outputs, strict=True):
            completion = output.outputs[0]
            responses.append(
                GenResponse(
                    request_id=request.request_id,
                    text=str(completion.text).strip(),
                    backend=self.name,
                    model_revision=self.model_revision(request.model),
                    prompt_tokens=len(getattr(output, "prompt_token_ids", ()) or ()),
                    completion_tokens=len(getattr(completion, "token_ids", ()) or ()),
                )
            )
        return responses

    def _dispatch(self, engine: Any, prompts: list[str], params: list[Any]) -> Any:
        """One ``engine.generate`` call, with vLLM's own progress bar suppressed.

        The scheduler dispatches one call per graph layer and one per probe wave, so a
        50x32 run makes thousands of calls. Each one draws its own tqdm bar, and on a
        detached tmux/`tee` log that is thousands of redraw blocks in the run log —
        enough to bury the lines that matter and to cost real time on a slow terminal.

        ``use_tqdm`` is passed positionally-safe as a keyword and the fallback exists for
        injected fake engines (and any vLLM version that drops the argument): a run must
        not fail because a progress bar could not be turned off.
        """
        if not self._accepts_use_tqdm:
            return engine.generate(prompts, params)
        try:
            return engine.generate(prompts, params, use_tqdm=False)
        except TypeError:
            # Retried at most once per backend instance: a TypeError raised from INSIDE
            # generate would otherwise be swallowed and the batch silently run twice.
            self._accepts_use_tqdm = False
            return engine.generate(prompts, params)

    def _render(self, request: GenRequest) -> str:
        """Apply the chat template through the engine's own tokenizer.

        Going through the engine's tokenizer rather than a separately loaded one is what
        keeps the serialized prompt identical to what the engine will actually see.
        """
        engine = self._ensure_engine()
        get_tok = getattr(engine, "get_tokenizer", None)
        tokenizer = get_tok() if callable(get_tok) else None
        if tokenizer is None or not getattr(tokenizer, "chat_template", None):
            return request.prompt
        messages = []
        if request.system:
            messages.append({"role": "system", "content": request.system})
        messages.append({"role": "user", "content": request.prompt})
        return str(
            tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        )

    def model_revision(self, model: str) -> str | None:
        if model not in self.profiles:
            raise KeyError(f"unknown model profile '{model}'; have {list(self.profiles)}")
        return f"{self.model_path}@{self.revision or 'unresolved'}"

    def resolved_revisions(self) -> dict[str, str | None]:
        """The commit SHAs the Hub actually resolved, not the ones we asked for.

        A pinned revision that is a branch name, a tag, or a short SHA resolves to
        something; recording the request as though it were the outcome cannot tell the
        difference. Best-effort and cached: never fails a finished run.
        """
        if self._resolved is not None:
            return self._resolved
        out: dict[str, str | None] = {
            "requested_model_revision": self.revision,
            "requested_tokenizer_revision": self.tokenizer_revision,
            "model_repo": self.model_path,
            "tokenizer_repo": self.tokenizer_path,
        }
        try:
            import os

            from huggingface_hub import HfApi

            api = HfApi(token=os.environ.get("HF_TOKEN"))
            out["resolved_model_sha"] = api.model_info(self.model_path, revision=self.revision).sha
            out["resolved_tokenizer_sha"] = api.model_info(
                self.tokenizer_path, revision=self.tokenizer_revision
            ).sha
            out["model_pin_exact"] = str(out["resolved_model_sha"] == self.revision)
            out["tokenizer_pin_exact"] = str(
                out["resolved_tokenizer_sha"] == self.tokenizer_revision
            )
        except Exception as exc:  # provenance is best-effort, never a gate here
            out["error"] = f"{type(exc).__name__}: {exc}"
        self._resolved = out
        return out

    def shared_handle_ids(self) -> dict[str, int]:
        """All profiles share one engine, which is the point of the 3090 plan."""
        return {profile: id(self) for profile in sorted(self.profiles)}

    def close(self) -> None:
        self._engine = None


class _SamplingParamsShim:  # pragma: no cover - only used when vllm is absent
    """Stand-in so an injected fake engine can be exercised without vllm installed."""

    def __init__(self, **kwargs: Any) -> None:
        self.__dict__.update(kwargs)
