"""Real Transformers sampling contract; excluded from the offline CPU gate."""

from __future__ import annotations

import hashlib

import pytest
import torch
import transformers

from rdl.models.loader import (
    LEAKK_OFFICIAL_GENERATE_KWARGS,
    HFLMHandle,
    clean_leakk_official_output,
    leakk_official_inputs,
)
from rdl.models.stub import GenerationRequest


@pytest.mark.network
def test_sampled_hf_generation_is_seeded_without_generator_model_kwarg() -> None:
    model_id = "hf-internal-testing/tiny-random-gpt2"
    tokenizer = transformers.AutoTokenizer.from_pretrained(model_id)
    tokenizer.pad_token = tokenizer.eos_token
    model = transformers.AutoModelForCausalLM.from_pretrained(model_id).to("cpu").eval()
    handle = HFLMHandle(model, tokenizer, model_id=model_id, dtype="float32", attn="eager")
    prompt = "A short scientific answer is"
    same = GenerationRequest(do_sample=True, temperature=1.0, top_p=1.0, seed=91)
    assert handle.generate(
        prompt, max_new_tokens=12, apply_template=False, request=same
    ) == handle.generate(prompt, max_new_tokens=12, apply_template=False, request=same)
    provenance = handle.generation_provenance()
    assert provenance["semantic_user_prompt_sha256"] == hashlib.sha256(prompt.encode()).hexdigest()
    assert provenance["serialized_chat_prompt_sha256"] == provenance["semantic_user_prompt_sha256"]
    assert provenance["input_ids_sha256"] and len(provenance["input_ids_sha256"]) == 64
    # Sampling may collide on a very small model, but several independent seeds should
    # expose more than one continuation and, crucially, no unsupported generator kwarg.
    outputs = {
        handle.generate(
            prompt,
            max_new_tokens=12,
            apply_template=False,
            request=GenerationRequest(do_sample=True, temperature=1.0, top_p=1.0, seed=seed),
        )
        for seed in range(4)
    }
    assert len(outputs) > 1
    assert torch is not None


@pytest.mark.network
def test_leakk_official_prompt_path_matches_real_tofu_rule_golden() -> None:
    """Pin the released tokenizer and a real TOFU forget10 question byte-for-byte.

    These expected IDs were generated by Leak-k e544af6's `pass_k_per_query` route:
    template IDs -> decode(skip_special_tokens=True) -> tokenize(add_special_tokens=True).
    No model weights are loaded, so this stays a small network contract while covering
    the actual direct Leak@k compatibility path.
    """
    tokenizer = transformers.AutoTokenizer.from_pretrained(
        "OptimAI-Lab/TOFU-forget10_RULE-NPO",
        revision="afe117e41a876f815bbd0f336d5036ced666ab06",
    )
    question = (
        "What is the full name of the author born in Taipei, Taiwan on 05/11/1991 "
        "who writes in the genre of leadership?"
    )
    serialized, template_ids, input_ids = leakk_official_inputs(tokenizer, question)
    assert serialized == (
        "system\n\nCutting Knowledge Date: December 2023\nToday Date: 10 Apr 2025\n\n"
        "You are a helpful assistant.user\n\nWhat is the full name of the author born in "
        "Taipei, Taiwan on 05/11/1991 who writes in the genre of leadership?assistant\n\n"
    )
    assert template_ids == [
        128000,
        128006,
        9125,
        128007,
        271,
        38766,
        1303,
        33025,
        2696,
        25,
        6790,
        220,
        2366,
        18,
        198,
        15724,
        2696,
        25,
        220,
        605,
        5186,
        220,
        2366,
        20,
        271,
        2675,
        527,
        264,
        11190,
        18328,
        13,
        128009,
        128006,
        882,
        128007,
        271,
        3923,
        374,
        279,
        2539,
        836,
        315,
        279,
        3229,
        9405,
        304,
        97445,
        11,
        29389,
        389,
        220,
        2304,
        14,
        806,
        14,
        2550,
        16,
        889,
        14238,
        304,
        279,
        17779,
        315,
        11692,
        30,
        128009,
        128006,
        78191,
        128007,
        271,
    ]
    assert input_ids == [
        128000,
        9125,
        271,
        38766,
        1303,
        33025,
        2696,
        25,
        6790,
        220,
        2366,
        18,
        198,
        15724,
        2696,
        25,
        220,
        605,
        5186,
        220,
        2366,
        20,
        271,
        2675,
        527,
        264,
        11190,
        18328,
        3405,
        271,
        3923,
        374,
        279,
        2539,
        836,
        315,
        279,
        3229,
        9405,
        304,
        97445,
        11,
        29389,
        389,
        220,
        2304,
        14,
        806,
        14,
        2550,
        16,
        889,
        14238,
        304,
        279,
        17779,
        315,
        11692,
        30,
        78191,
        271,
    ]
    assert LEAKK_OFFICIAL_GENERATE_KWARGS == {
        "max_new_tokens": 200,
        "do_sample": True,
        "num_return_sequences": 1,
        "top_p": 1.0,
        "temperature": 1.0,
    }
    assert (
        clean_leakk_official_output(serialized, serialized + " A continuation. ")
        == "A continuation."
    )
