#!/usr/bin/env bash
# GENERATED by `rdl graph-detector-v4-2-plan-bank-runs`. Do not edit:
# every seed here is pre-registered in ENGINEERING_BANK_MANIFEST.json and
# `build-bank` verifies the runs against it.
set -euo pipefail

# natural seed 50241
python -m rdl.cli graph-run --launch configs/graph/launch.yaml --profile rtx3090_1b --cohort data/cohorts/graph_unlearning_v1/discovery.json --protocol graph_flow --challenges natural --n-samples 32 --base-seed 50241 --output runs/graph/engineering-natural-seed50241

# natural seed 50242
python -m rdl.cli graph-run --launch configs/graph/launch.yaml --profile rtx3090_1b --cohort data/cohorts/graph_unlearning_v1/discovery.json --protocol graph_flow --challenges natural --n-samples 32 --base-seed 50242 --output runs/graph/engineering-natural-seed50242

# natural seed 50243
python -m rdl.cli graph-run --launch configs/graph/launch.yaml --profile rtx3090_1b --cohort data/cohorts/graph_unlearning_v1/discovery.json --protocol graph_flow --challenges natural --n-samples 32 --base-seed 50243 --output runs/graph/engineering-natural-seed50243

# natural seed 50244
python -m rdl.cli graph-run --launch configs/graph/launch.yaml --profile rtx3090_1b --cohort data/cohorts/graph_unlearning_v1/discovery.json --protocol graph_flow --challenges natural --n-samples 32 --base-seed 50244 --output runs/graph/engineering-natural-seed50244

# retain seed 51241
python -m rdl.cli graph-run --launch configs/graph/launch.yaml --profile rtx3090_1b --cohort data/cohorts/graph_unlearning_v1/retain_utility.json --protocol graph_flow --challenges natural --n-samples 32 --base-seed 51241 --output runs/graph/engineering-retain-seed51241

# retain seed 51242
python -m rdl.cli graph-run --launch configs/graph/launch.yaml --profile rtx3090_1b --cohort data/cohorts/graph_unlearning_v1/retain_utility.json --protocol graph_flow --challenges natural --n-samples 32 --base-seed 51242 --output runs/graph/engineering-retain-seed51242

# retain seed 51243
python -m rdl.cli graph-run --launch configs/graph/launch.yaml --profile rtx3090_1b --cohort data/cohorts/graph_unlearning_v1/retain_utility.json --protocol graph_flow --challenges natural --n-samples 32 --base-seed 51243 --output runs/graph/engineering-retain-seed51243

# retain seed 51244
python -m rdl.cli graph-run --launch configs/graph/launch.yaml --profile rtx3090_1b --cohort data/cohorts/graph_unlearning_v1/retain_utility.json --protocol graph_flow --challenges natural --n-samples 32 --base-seed 51244 --output runs/graph/engineering-retain-seed51244

